### ISSUE TITLE
bounds on alpha in fitContinuous(model = "OU")

### ISSUE THREAD

**Issue by davharris** [mwpennell/geiger-v2#12]
I seem to have found a mismatch between `fitContinuous`'s behavior and its documentation (version 2.0.3, from CRAN).

The documentation for `fitContinuous` with `model == "OU"` says "Default bounds are `alpha = c(min = 0, max = 150)`".

But when I fit a model with the default options and look at its bounds, I get `alpha` bounded between 0 and `exp(1)` (about 2.7).

```
fit =  fitContinuous(phylogeny, x, model = "OU")
fit$bnd
                 mn           mx
alpha 7.124576e-218 2.718282e+00
sigsq 7.124576e-218 2.688117e+43
```
I noticed this because I keep bumping up against the upper bound.

Should the behavior be changed to match the documentation (or vice versa)? Sorry if I'm missing something obvious.

**Comment by lukejharmon** [comment]
You are absolutely right. I changed the documentation to match the behavior of the function (rather than the other way around). You should be able to install the new version here using devtools. Please let me know or reopen if you have more questions!

**Comment by davharris** [comment]
Okay, great.  thanks for the quick response.
