### ISSUE TITLE
fitDiscrete fails when traits are, um, actually discrete?

### ISSUE THREAD

**Issue by cboettig** [mwpennell/geiger-v2#16]
It looks like `fitDiscrete` takes numeric (doubles) but not integer-valued traits?  From the example,

```r
## match data and tree
tmp=get(data(geospiza))
td=treedata(tmp$phy, tmp$dat)
geo=list(phy=td$phy, dat=td$data)
```

And now let's use `as.integer` to make sure we're actually using discrete values instead of continuous values:

```r
gb= as.integer(round(geo$dat[,5])) ## create discrete data
names(gb)=rownames(geo$dat)
tmp=fitDiscrete(geo$phy, gb, model="ER", control=list(niter=5), ncores=2)
```

I get this error:

```
.check.states(tree, states, strict.vals = 1:k) : 
  The states vector must contain names
```

Of course dropping the `as.integer` things work fine.  Maybe I'm missing something here.

**Comment by josephwb** [comment]
@cboettig fixed with https://github.com/mwpennell/geiger-v2/pull/17  :neckbeard:

**Comment by cboettig** [comment]
nice, thanks!
