### ISSUE TITLE
sim.bdtree does not check correct parameter use

### ISSUE THREAD

**Issue by richelbilderbeek** [mwpennell/geiger-v2#19]
Hi Matthew,

I noticed it is easy to misuse sim.bdtree, as this code may convince you of:

```
library(geiger)

# Should give error: 'if stopping criterium is set to 'time', please do not set the number of taxa 'n'
sim.bdtree(b = 0.4, d = 0.1, stop = "time", n = 10, t = 10)
# Should give error: 'if stopping criterium is set to 'taxa', please do not set the time of the simulation 't'
sim.bdtree(b = 0.4, d = 0.1, stop = "taxa", n = 10, t = 10)
# Should give error: 'if stopping criterium is set to 'time', please provide a value for 'n''
sim.bdtree(b = 0.4, d = 0.1, stop = "time", n = 10)
# Should give error: 'if stopping criterium is set to 'taxa', please provide a value for 'n''
sim.bdtree(b = 0.4, d = 0.1, stop = "taxa", t = 10)
```

It would have saved me some debugging if geiger did check its arguments.

Could you fix it? If you assign me, I will provide a pull request. Note that I will change the default parameters for `n` and `t` to `NA` or `NULL`, but I do not expect this to break code (yet I may be wrong).

**Comment by richelbilderbeek** [comment]
Hi @lukejharmon, for what reason is this Issue closed? Has it been done or will the suggestion be ignored?

**Comment by lukejharmon** [comment]
Neither - I implemented it but neither pushed the change nor commented here. My mistake! But it has been done now - see this [commit](https://github.com/mwpennell/geiger-v2/commit/59944790f6ed1d3378e735dcfaf51ab1538eddfb)

**Comment by richelbilderbeek** [comment]
Awesome! Thanks :+1:
