### ISSUE TITLE
Update changelog to reflect changes from geiger 1.3

### ISSUE THREAD

**Issue by cboettig** [mwpennell/geiger-v2#2]
The ChangeLog doesn't really do justice to all the improvements and additions between geiger 1.3.1 and 1.99.2. It would be nice to have a concise summary of these somewhere (maybe already exists and can just be linked from the ChangeLog?)  

I'd also consider adding version numbers next to the dates in the ChangeLog. 

Just suggestions, feel free to close if not helpful.

**Comment by lukejharmon** [comment]
I added a link to the geiger 2.0 paper - I know that is a path of least resistance. We have started keeping better notes on the changelog now.
