### ISSUE TITLE
fitContinuous - input argument names and documentation names are very confusing

### ISSUE THREAD

**Issue by lukejharmon** [mwpennell/geiger-v2#25]
When people discuss evolutionary trends in the literature, they usually mean changes in the mean trait value through time. But in fitContinuous this is called "drift" - which conjures genetic drift and, probably, is confusing to everyone. Then what we call the trend model is a trend in the rate, and is very similar to EB - but there is really no way to know that from the documentation.

This is a bit of a sad state. I suggest changing this but in a way that maintains backwards compatibility with people's code - that is, add two new arguments for these two models that are more intuitive, like meanTrend and rateTrend, and (silently) accept the old arguments as well.

**Comment by liamrevell** [comment]
I made this changes - but called the models `"mean_trend"` and `"rate_trend"` while maintaining backward compatibility (that is, `"drift"` and `"trend"` are still accepted).

I then went to update the model names in `fitContinuousMCMC` - but I discovered they are all totally different & gave up!
