### ISSUE TITLE
MEDUSA issue with 'old' trees

### ISSUE THREAD

**Issue by A-Swafford** [mwpennell/geiger-v2#28]
Hello,
I'm attempting to use MEDUSA on a large tree that is ~850MY old at the root (cumulative branch length from any tip to root >800).  When I attempt to run Medusa, I get the following error:

```
Appropriate  aicc-threshold for a tree of 3973 tips is: 11.90177.

Error in optim(fn = foo, par = log(sp), method = "N") : 
  function cannot be evaluated at initial parameters
```

However, if I set all the edges in $edge.length to 1 and run Medusa, it begins taking steps as expected.

Any help or insight would be greatly appreciated!

**Comment by josephwb** [comment]
@A-Swafford Can you try [this version](https://github.com/josephwb/turboMEDUSA)? Alternatively, please send me your tree file to troubleshoot (phylo dot jwb at gmail dot com).

**Comment by josephwb** [comment]
I have no idea why setting all edge lengths to 1 would work. Doesn't that make it non-ultrametric? Or do you mean rescaling the tree so that the root has an age of 1?

**Comment by josephwb** [comment]
The tree seems to have a problem passing ultrametricity test, presumably because of many rounding errors accumulating. Rescaling the tree circumvents the problem:
```R
> is.ultrametric(phy)
[1] FALSE
> fie <- phy
> fie$edge.length <- fie$edge.length * 0.1
> is.ultrametric(fie)
[1] TRUE
```
So, closing.
