### ISSUE TITLE
fitDiscrete - fn does not return complete Q matrix

### ISSUE THREAD

**Issue by Caetanods** [mwpennell/geiger-v2#30]
Function does not return the complete Q matrix as a 'matrix' object. The function print the matrix to the screen only.
The Q matrix in a 'matrix' format, rather than a vector of parameters ( see 'coef( fitDistrete(...) )' ), is important to apply in further analyses.

**Comment by Caetanods** [comment]
I finally learned that the hidden 'geiger' function "geiger:::.Qmatrix.from.gfit()" will transform the output from geiger back to a Q matrix format that can be used for downstream analysis.

I suggest this function to be incorporated to 'fitDiscrete'. In my point of view, the final fit of a Mk model is the transition matrix.

**Comment by liamrevell** [comment]
I just defined and added a new S3 method as.Qmatrix that will return the Q-matrix from the "gfit" object class.
