### ISSUE TITLE
Maintainer of geiger?

### ISSUE THREAD

**Issue by richelbilderbeek** [mwpennell/geiger-v2#38]
[According to CRAN](https://CRAN.R-project.org/package=geiger), `geiger` is an orphaned package, but according to [this repo's DESCRIPTION file](https://github.com/mwpennell/geiger-v2/blob/master/DESCRIPTION#L8), Luke Harmon is the maintainer.

Which of the one is true?

**Comment by dwbapst** [comment]
@richelbilderbeek I share your concerns. I first noticed the orphaned listing in June, and both @bomeara and I became concerned and so I emailed @mwpennell and and @lukejharmon, neither of whom responded. A very worrying situation.

Does anyone know what is going on with geiger? @liamrevell do you know?

I get particularly worried when I see all the packages that have geiver listed as an essential import/depends:

```
Reverse depends: | bayou, convevol, DAMOCLES, iteRates, OUwie, surface, TreeSim, windex
-- | --
Reverse imports: | beautier, BMhyb, BMhyd, dispRity, entropart, evobiR, hilldiv, lefse, metricTester, ouxy, pcmabc, PhyInformR, phylocurve, pmc, ratematrix, RPANDA, Rphylopars, RRphylo, secsse, sensiPhy, treeplyr
Reverse suggests: | BBMV, diversitree, fishtree, ouch, phytools, RNeXML, tracerer
```

Tagging @uyedaj or @tguillerme as their packages are in among these

**Comment by lukejharmon** [comment]
I just submitted a new, unorphaned version to CRAN. I am on the hook for this going forwards.

**Comment by dwbapst** [comment]
@lukejharmon in the future, feel free to let us (those of us who follow this repository) know if you run into any rough CRAN / travis problems with R CHECK! I think many of us care about keeping geiger available on CRAN for the community, and it might be easy fixes for some of us with more actively-updating packages. 

I hope all is swell in Idaho!
