### ISSUE TITLE
geiger considered orphaned by CRAN

### ISSUE THREAD

**Issue by marlonecobos** [mwpennell/geiger-v2#39]
Hi,
It looks like CRAN is currently considering geiger as an orphaned package, 

"X-CRAN-Comment Orphaned and corrected on 2019-01-16 as no response to
request for corrections"

I was trying to submit a package to CRAN and received a Warning because of that. I hope it is not true.

Best,

**Comment by mwpennell** [comment]
Yes, we are aware of this. Working now to get it back to being maintained. (Need to do some things to get a new version approved by CRAN)

**Comment by marlonecobos** [comment]
Thanks for the rapid response.

**Comment by liamrevell** [comment]
No longer orphaned.
