### ISSUE TITLE
MEDUSA results over a distribution of trees?

### ISSUE THREAD

**Issue by LauravanHolstein** [mwpennell/geiger-v2#40]
Hello! 

I've just run medusa on 100 trees, but I can't seem to find anything akin to the options for plotting results over a distribution of trees à la the TurboMedusa or Medusa packages (which I can't install as they're not available for my version (3.6.0) of R. I'd like something like the example output here: https://github.com/josephwb/turboMEDUSA. Am I missing something really obvious? 

My temporary workaround is summarising the frequency of a shift happening at a given node using simple bar charts, but I liked the elegance of the old plotting functionalities of the turboMedusa/Medusa packages! 

Thanks and sorry for the potential derpiness of this question... 
Laura

**Comment by josephwb** [comment]
I apologize. Not all of the summary functions from turboMEDUSA made it into geiger (my fault entirely).

What happens when you try this:
```
install.packages("devtools");
library(devtools);
install_github("josephwb/turboMEDUSA/MEDUSA", dependencies=TRUE);
```

**Comment by LauravanHolstein** [comment]
Hi Joseph!

Thanks for getting back to me so quickly! 

Installed like a dream. Thanks so much. 

However, I now get an error when I pass the multiMedusaSummary to plotMultiMedusa:

```
result<- MEDUSA(trees, richness, criterion="aicc")
summary<-multiMedusaSummary(result, cntree, plotTree=F, cutOff=0.05)
plotMultiMedusa(summary, treeRearrange="down", annotateShift=TRUE, annotateRate="r.median",
                plotRichnesses=TRUE, richPlot="log", time=TRUE, tip.cex=0.3, shiftScale=1, label.offset=0.5, font=3,
                shift.leg.pos="left", power=1.5, pal=1, revColours=FALSE)
```

The error I get: 
`Error in 0:maxVal : NA/NaN argument
In addition: Warning message:
In Ops.factor(richness$n.taxa, 1) : ‘+’ not meaningful for factors`

I'm sure I can figure it out with enough time and coffee but any help would be appreciated. Thanks in advance!

**Comment by LauravanHolstein** [comment]
Also, no need to apologise for not including these in geiger, it's an awesome package and I'm really grateful for all your efforts.

**Comment by josephwb** [comment]
Oi. There is a lot of indexing going on that is difficult to follow.

Can you email me the input data (trees and richness)? phylo.jwb@gmail.com

I will try to get to this today.

**Comment by lukejharmon** [comment]
I assume that this got resolved and am closing.
