### ISSUE TITLE
install.packages("geiger") error

### ISSUE THREAD

**Issue by 1457634627** [mwpennell/geiger-v2#42]
make: *** [/usr/lib64/R/etc/Makeconf:172: foreign-graphml.o] Error 1
ERROR: compilation failed for package ‘igraph’
* removing ‘/usr/lib64/R/library/igraph’
ERROR: dependency ‘igraph’ is not available for package ‘phangorn’
* removing ‘/usr/lib64/R/library/phangorn’
ERROR: dependency ‘phangorn’ is not available for package ‘phytools’
* removing ‘/usr/lib64/R/library/phytools’
ERROR: dependency ‘phytools’ is not available for package ‘geiger’
* removing ‘/usr/lib64/R/library/geiger’

The downloaded source packages are in
	‘/tmp/RtmpqU6Eiy/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning messages:
1: In install.packages("geiger") :
  installation of package ‘igraph’ had non-zero exit status
2: In install.packages("geiger") :
  installation of package ‘phangorn’ had non-zero exit status
3: In install.packages("geiger") :
  installation of package ‘phytools’ had non-zero exit status
4: In install.packages("geiger") :
  installation of package ‘geiger’ had non-zero exit status

How can I solve this problem ？
Thanks

**Comment by imk1** [comment]
I am having the same issue.  Thanks!

**Comment by liamrevell** [comment]
It seems like _igraph_ will not install. Are you working on Windows or some other operating system?

**Comment by imk1** [comment]
igraph was not a problem for me, but phytools was.  I am using a linux cluster.  It seems like geiger is defaulting to install a version that is not compatible with my verison of R, even though there are versions of geiger that are compatible.

**Comment by liamrevell** [comment]
What is your version of R?

**Comment by imk1** [comment]
I tried R 3.6.0, and that did not work.  I then tried R 4.2.2, and that worked.

**Comment by liamrevell** [comment]
Great!
